### ISSUE TITLE
吴景选择使用决斗合击时无法使用决斗

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#693]
## 描述出现的 Bug
当一名角色使用决斗后，吴景弹窗选择使用决斗合击，然后选择使用决斗时无法选择包含决斗在内的牌

## 备注
使用红杀后合击决斗不知道是否也会触发

**Comment by DZDcyj** [comment]
系 pattern 开头小写所致
