### ISSUE TITLE
群友包武将平衡性调整和重做

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#773]
## 需要重做的武将包括
饿人类（重做晒卡）、秋目（完全重做）、磷酸（完全重做）、暗暗（重做并适当加强）

## 需要调整平衡的武将包括
sp仙人掌（削弱绝杀）、sp磷酸（削弱缴械）、终了（修改锐评技能）、夜鸟（削弱附魔效果数量）、林夕（加强）

**Comment by Cactusssssssss** [comment]
绝杀：当一名角色在濒死结算期间第一次成为桃或酒的目标时，你可以令该桃或酒失效。若你于回合外发动此技能，则此技能失效直到你的下一个回合开始。

**Comment by Cactusssssssss** [comment]
缴械：当一名角色对你造成伤害后，你可以选择以下一项执行：1.废除伤害来源的装备区直到该角色的下个回合开始，然后其本回合使用x张牌后，不能再使用牌（x为你的体力值）；2.令伤害来源本回合不能对其他角色使用牌，且防止其本回合造成的所有伤害直到回合结束。

**Comment by DZDcyj** [comment]
涉及过多可以拆成多个 issue
