### ISSUE TITLE
米糠

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#803]
## 基本信息
所属包：群友包
势力：吴
称号：督军
性别：男

4 勾玉

## 技能描述
【督战】出牌阶段限一次，你可以将一张牌交给一名其他角色，该角色需对你指定的另一名角色使用一张杀，否则你获得其一张牌，并视为对其使用一张无距离与次数限制且不计入次数的杀
【勉励】每回合限一次，一名角色的出牌阶段开始时，你可以展示并交给其一张牌，然后令其选择一项整肃。弃牌阶段结束时，若其整肃成功，其选择一项整肃奖励获得并执行一个额外的出牌阶段
【请功】当一名角色于其摸牌阶段外一次性获得至少两张牌时，或于其出牌阶段外回复体力时，你可以摸一张牌

**Comment by DZDcyj** [comment]
整肃判断时机在弃牌阶段结束后，将额外出牌阶段放在结束阶段进行

**Comment by Cactusssssssss** [comment]
请功发动次数过于频繁，需要削弱触发频率；
督战影响整肃，需要修改至不影响整肃，以中和请功带来的强度降低；
整体的强度是下降的。
（但是我没想好怎么修改）
勉励技能名得改一下

**Comment by Cactusssssssss** [comment]
修改技能
【督战】出牌阶段限一次，你可以将一张牌交给一名其他角色，然后该角色需对你指定的另一名角色使用一张杀，否则你获得其一张牌，并选择以下一项1.令其弃置两张牌，2，对其造成一点伤害
【勉励】修改技能名为【励行】
【请功】每回合限两次，当一名角色于其摸牌阶段外一次性获得至少两张牌时，或于其出牌阶段外回复体力时，你可以摸一张牌
