### ISSUE TITLE
界左慈

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#855]
## 基本信息
所属包：扩展武将包
势力：群
称号：迷之仙人
性别：男

3 勾玉

## 技能描述
【化身】①游戏开始时，你随机获得三张武将牌作为“化身”牌，然后你选择其中一张“化身”牌的一个技能并亮出之，然后你视为拥有此技能，且性别和势力视为与“化身”牌相同。
        ②回合开始或结束时，你可以选择一项：1.重新进行一次“化身”；2.移去至多两张不为亮出的“化身”牌，然后获得等量的新“化身”牌。
【新生】当你受到1点伤害后，若你有技能“化身”，你可以随机获得一张新的“化身”牌。

**Comment by DZDcyj** [comment]
![image](https://github.com/DZDcyj/QSGS-v2-Lua/assets/42711105/b6134f38-33d7-4673-be18-c4216b844350)

暂时先不搞了
