### ISSUE TITLE
砂糖武将调整

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#856]
调整砂糖支援
【支援】准备阶段，你可以令任意名手牌数不大于体力值的角色各摸1张牌，或令一名手牌数大于体力值的角色回复1点体力

**Comment by DZDcyj** [comment]
> 调整砂糖支援 【支援】准备阶段，你可以令任意名手牌数不大于体力值的角色各摸1张牌，或令一名手牌数大于体力值的角色回复1点体力

<s>每回合各限一次，</s>准备阶段<s>与结束阶段</s>，你可以令任意名手牌数不大于体力值的角色各摸1张牌，或令一名手牌数大于体力值的角色回复1点体力

对比原版修改，少去结束阶段
