### ISSUE TITLE
董承

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#896]
## 基本信息
所属包：sp（扩展武将包）
势力：群
称号：沥胆卫汉
性别：男

4 勾玉

## 技能描述
【承诏】一名角色的结束阶段，若你本回合获得过至少两张牌，你可以与一名角色拼点，若你赢，视为你对其使用一张无视防具的【杀】

**Comment by DZDcyj** [comment]
2024/03/03 讨论，考虑将触发时机调整为 结束阶段结束时
