### ISSUE TITLE
旧郭嘉遗计Bug

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#898]
## 描述出现的 Bug
旧遗计结算给牌时，存在一个短暂的时机复制卡牌，复制卡牌会导致意外结算。
如：旧郭嘉界夏侯，遗计将牌留给自己时，会导致复制卡牌给其他角色的bug

## 备注
曹金玉也会

**Comment by DZDcyj** [comment]
根因在于 askForYiji 的结算方式，无法调整源码结算，修正【清俭】，防止选择相同 id 牌
