### ISSUE TITLE
整肃逻辑调整

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#913]
目前整肃逻辑为弃牌阶段结束时判断是否整肃成功，考虑到以后新将可能需要于出牌阶段及时判断整肃是否失败，希望修改整肃底层逻辑。

**Comment by DZDcyj** [comment]
整肃逻辑调整方案：
1. 需要新增失败处理逻辑接口，用于失败场景回调（默认播放失败台词语音）
2. 整肃中途记录需要增加失败判断，并添加失败标记用于避免二次检测和回调

**Comment by DZDcyj** [comment]
协力机制也需要同样调整，因不存在过程中失败，只引入即时成功回调接口
