### ISSUE TITLE
孙翊 躁厉与木牛流马不能正确使用

### ISSUE THREAD

**Issue by Cactusssssssss** [DZDcyj/QSGS-v2-Lua#922]
## 描述出现的 Bug
孙翊回合内将不能使用的牌放入木牛流马后，将再也无法使用木牛流马内的牌。

## 备注
将木牛流马转移给其他人后，其他人可以正常使用那些牌

[孙翊牛马bug.txt](https://github.com/user-attachments/files/17179318/bug.txt)

**Comment by DZDcyj** [comment]
在躁厉解除卡牌限制过程中，只遍历了手牌，导致此时不在手牌区内的卡牌受影响

**Comment by DZDcyj** [comment]
> 在躁厉解除卡牌限制过程中，只遍历了手牌，导致此时不在手牌区内的卡牌受影响

现有的逻辑如下
1. 当本回合有新卡牌进入手牌区时，为角色添加卡牌对应的标记
2. 出牌阶段开始时，遍历**手牌区**，将所有未在 1 中有标记的卡牌封禁
3. 出牌阶段结束时，遍历**手牌区**，解除对应的封禁

若有在阶段 2 中被封禁，然后在 3 阶段未被解封的卡牌，则无法使用。通常是在这段时间内移动过后导致，包括但不限于木牛流马、装备区移动等

解决方案考虑在解封时走全量？

**Comment by DZDcyj** [comment]
考虑修改封禁、解封范围，方案如下
1. 封禁时，除去遍历手牌区，还需要遍历所有私家牌堆（如木牛流马、星甘宁【铃】等，均是末尾带 & 的）
2. 解封时，可全量解除，无需针对是否有对应的卡牌标记进行判断

**Comment by DZDcyj** [comment]
遗留问题需要测试：若封禁私家牌堆，涉及到转化技能（如邓艾【田】）的，需要额外讨论

**Comment by DZDcyj** [comment]
> 遗留问题需要测试：若封禁私家牌堆，涉及到转化技能（如邓艾【田】）的，需要额外讨论

与 @Cactusssssssss 讨论结果如下
技能描述修改为: 不能使用或打出非本回合内进入手牌区的手牌，而非仅能使用 XXX
